version: "3"

services:
  nestjs:
    container_name: nestjs
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - nestjs-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3030:3000"
      - "5555:5555"
    volumes:
      - ./:/work
    tty: true
    restart: always

networks:
  reverse-proxy-network:
    external: true
