version: "3"

services:
  nuxt:
    container_name: nuxt
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - nuxt-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./:/work
    tty: true
    restart: always

networks:
  reverse-proxy-network:
    external: true
